/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Little;

import DomainModel.D_SanPhamBig;
import DomainModel.D_SoKhung;
import ServiceImpl.CTSanPhamImpl;
import ServiceImpl.little.SoKhungImpl;
import View.View_SanPhamBig;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VietTien
 */
public class View_SoKhung extends javax.swing.JFrame {

    private final SoKhungImpl S_soKhung;
    private final CTSanPhamImpl S_CTSP;
    private SoKhungImpl s_Sk = new SoKhungImpl();

    public View_SoKhung() {
        initComponents();
        setLocationRelativeTo(null);
        this.S_soKhung = new SoKhungImpl();
        this.S_CTSP = new CTSanPhamImpl();
        loadMSP(s_Sk.getMSP());
        rdoChua.setSelected(true);
    }

    public View_SoKhung(View_SanPhamBig sanPhamBig) {
        initComponents();
        setLocationRelativeTo(null);
        this.S_soKhung = new SoKhungImpl();
        this.S_CTSP = new CTSanPhamImpl();
        loadMSP(s_Sk.getMSP());
        rdoChua.setSelected(true);
    }

    public View_SoKhung(D_SanPhamBig sp) {
        initComponents();
        setLocationRelativeTo(null);
        this.S_soKhung = new SoKhungImpl();
        this.S_CTSP = new CTSanPhamImpl();
        List<D_SoKhung> listSK = S_soKhung.getAllByNameMaSP(sp.getMaSP());
        loadData(listSK);
        rdoChua.setSelected(true);
    }

    public void loadData(List<D_SoKhung> sk) {

        DefaultTableModel dtm = (DefaultTableModel) tlbBang.getModel();
        dtm.setRowCount(0);
        int stt = 1;
        for (D_SoKhung x : sk) {

            dtm.addRow(new Object[]{
                stt,
                x.getId(),
                x.getCtsp().getMaSP(),
                x.getSoKhung(),
                x.getTrangThai() == 1 ? "Chưa Bán" : "Đã Bán"});

            stt++;
        }
    }

    public void loadMSP(ArrayList<String> list) {
        cbbMSP.removeAllItems();
        DefaultComboBoxModel defaultComBoboxModel = (DefaultComboBoxModel) cbbMSP.getModel();

        for (String string : list) {
            defaultComBoboxModel.addElement(string);
        }

    }

    public D_SoKhung getForm() {
        D_SoKhung kh = new D_SoKhung();
        kh.setId(txtId.getText());

        String index7 = cbbMSP.getSelectedItem().toString();
        D_SanPhamBig dtbx7 = S_CTSP.getOne(index7);
        kh.setCtsp(dtbx7);

//        String soKhungRandom = generateRandomSoKhung();
//        kh.setSoKhung(soKhungRandom);
        kh.setSoKhung(txtSoKhung.getText());
        int t = 0;
        if (rdoChua.isSelected()) {
            t = 1;
        }
        kh.setTrangThai(t);

        return kh;

    }
//

    private boolean isMaSPExists(String maSP) {
        List<String> danhSachMaSP = S_CTSP.getSoKhung();
        return danhSachMaSP.contains(maSP);
    }

    public boolean checkForm() {

        if (txtSoKhung.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được bỏ trống số khung");
            return false;
        }

        try {
            String sk = txtSoKhung.getText();

            // Kiểm tra định dạng 5 số - 5 số bằng Regular Expressions
            if (!sk.matches("\\d{5}-\\d{5}")) {
              
                 JOptionPane.showMessageDialog(this,
                    "Số khung không hợp lệ, vui lòng nhập theo định dạng xxxxx-xxxxx (vd: 25373-36478)",
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } catch (NumberFormatException e) {

             JOptionPane.showMessageDialog(this,
                    "Số khung không hợp lệ, vui lòng thử lại",
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Tiếp tục kiểm tra các trường khác nếu cần thiết
        return true;
    }
//    private String generateRandomSoKhung() {
//        Random rand = new Random();
//        int randomNum = rand.nextInt(90000) + 10000; // Sinh số ngẫu nhiên từ 10000 đến 99999
//        return String.valueOf(randomNum);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlbBang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbbMSP = new javax.swing.JComboBox<>();
        txtSoKhung = new javax.swing.JTextField();
        rdoChua = new javax.swing.JRadioButton();
        rdoDaBan = new javax.swing.JRadioButton();
        txtId = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Quản Lý Số Khung - Số Máy");

        tlbBang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tlbBang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Stt", "Id", "Mã Sản Phẩm", "Số Khung-Số Máy", "Trạng Thái"
            }
        ));
        tlbBang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tlbBangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tlbBang);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Mã Sản Phẩm :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Số Khung - Số Máy :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Trạng Thái");

        cbbMSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMSPActionPerformed(evt);
            }
        });

        rdoChua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoChua.setText("Chưa Bán");

        rdoDaBan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoDaBan.setText("Đã Bán");

        btnThem.setBackground(new java.awt.Color(0, 102, 102));
        btnThem.setForeground(new java.awt.Color(0, 102, 102));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/plus (1).png"))); // NOI18N
        btnThem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(0, 102, 102));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bin.png"))); // NOI18N
        btnXoa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm Kiếm"));

        jButton1.setText("Tìm Kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 255, 255));
        jButton2.setText("OK");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbbMSP, 0, 174, Short.MAX_VALUE)
                                .addComponent(txtSoKhung))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(rdoChua, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdoDaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap(127, Short.MAX_VALUE)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbMSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoKhung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoChua)
                            .addComponent(rdoDaBan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbMSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMSPActionPerformed
        String index7 = cbbMSP.getSelectedItem().toString();
//        D_ChiTietSanPham d = S_CTSP.getOne(index7);
//        System.out.println(d.getSanPham().getId());       
        List<D_SoKhung> list = s_Sk.getAllByNameMaSP(index7);
        loadData(list);
    }//GEN-LAST:event_cbbMSPActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int cf = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa dòng này");
        if (cf != JOptionPane.YES_OPTION) {
            return;
        }
        D_SoKhung d = this.getForm();
        S_soKhung.delete(d);

        JOptionPane.showMessageDialog(this, "Bạn đã xóa 1 dòng ");
        String index7 = cbbMSP.getSelectedItem().toString();
        List<D_SoKhung> list = s_Sk.getAllByNameMaSP(index7);
        loadData(list);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tlbBangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlbBangMouseClicked
        int row = tlbBang.getSelectedRow();
        if (row == -1) {
            return;
        }
        txtId.setText(tlbBang.getValueAt(row, 1).toString());
    }//GEN-LAST:event_tlbBangMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ma = txtTimKiem.getText().trim();
        if (ma.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập số khung cần tìm");
            return;
        }
        DefaultTableModel dtm = (DefaultTableModel) tlbBang.getModel();
        dtm.setRowCount(0);
        int count = 0;
        int stt = 1;
        for (D_SoKhung x : s_Sk.getAllSoKhung()) {
            if (x.getSoKhung().contains(ma)) {
                dtm.addRow(new Object[]{
                    stt,
                    x.getId(),
                    x.getCtsp().getMaSP(),
                    x.getSoKhung(),
                    x.getTrangThai() == 1 ? "Chưa Bán" : "Đã Bán"});

                stt++;
                count = 1;
            }
        }
        if (count == 0) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy mã sản phẩm hoặc tên sản phẩm nào như vậy");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (checkForm()) {
            D_SoKhung ds = this.getForm();
            if (ds != null) {

                String maSP = ds.getSoKhung();
                if (isMaSPExists(maSP)) {
                    JOptionPane.showMessageDialog(this,
                            "Số khung đã tồn tại!",
                            "Lỗi",
                            JOptionPane.ERROR_MESSAGE);
                } else {

                    if (this.S_soKhung.add(ds) != null) {
                        JOptionPane.showMessageDialog(this, "Bạn đã thêm thành công");
                        String index7 = cbbMSP.getSelectedItem().toString();
                        List<D_SoKhung> list = s_Sk.getAllByNameMaSP(index7);
                        loadData(list);
                    } else {
                        JOptionPane.showMessageDialog(this, "Có lỗi đang xảy ra");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        View_SanPhamBig v = new View_SanPhamBig();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_SoKhung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_SoKhung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_SoKhung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_SoKhung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_SoKhung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbMSP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoChua;
    private javax.swing.JRadioButton rdoDaBan;
    private javax.swing.JTable tlbBang;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtSoKhung;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
